% ORGANIZE_PROJECT - 整理项目文档结构
%
% 用法: organize_project()

function organize_project()
    fprintf('===== 整理项目文档 =====\n\n');
    
    % 1. 清理临时脚本
    fprintf('1. 清理临时脚本...\n');
    tempScripts = {
        'quick_visualize.m', ...
        'test_circle_detection.m', ...
        'test_irregular_defects.m'
    };
    
    for i = 1:length(tempScripts)
        script = tempScripts{i};
        if exist(script, 'file')
            delete(script);
            fprintf('   ✓ 删除: %s\n', script);
        end
    end
    
    % 2. 移动文档到docs/
    fprintf('\n2. 移动文档到docs/...\n');
    
    % 创建docs目录（如果不存在）
    docsDir = fullfile('..', 'docs');
    if ~exist(docsDir, 'dir')
        mkdir(docsDir);
        fprintf('   创建目录: docs/\n');
    end
    
    % 移动主文档
    mainDocs = {
        'V3.0-R6_FINAL_GUIDE.md'
    };
    
    for i = 1:length(mainDocs)
        doc = mainDocs{i};
        if exist(doc, 'file')
            targetPath = fullfile(docsDir, doc);
            try
                movefile(doc, targetPath);
                fprintf('   ✓ 移动: %s -> docs/\n', doc);
            catch
                fprintf('   ⚠ 跳过: %s (已存在或无法移动)\n', doc);
            end
        end
    end
    
    % 3. 创建docs/README.md索引
    fprintf('\n3. 创建文档索引...\n');
    readmePath = fullfile(docsDir, 'README.md');
    
    readmeContent = ['# 陶瓷缺陷检测系统 - 文档中心' newline newline ...
        '## 📚 文档列表' newline newline ...
        '### 主要文档' newline newline ...
        '- **[V3.0-R6_FINAL_GUIDE.md](V3.0-R6_FINAL_GUIDE.md)** - v3.0-R6最终使用指南（推荐阅读）' newline ...
        '  - 快速开始' newline ...
        '  - 参数调整' newline ...
        '  - 高级用法' newline ...
        '  - 常见问题' newline newline ...
        '### 版本文档' newline newline ...
        '详细的版本演进和技术细节请查看:' newline ...
        '- `../versions/CHANGELOG.md` - 完整版本历史' newline ...
        '- `../versions/v3.0_roi_detection/` - v3.0版本详细文档' newline newline ...
        '### 技术文档' newline newline ...
        '历史技术文档（已归档）:' newline ...
        '- CRITICAL_FIXES.md' newline ...
        '- OPTIMIZATION_SUMMARY.md' newline ...
        '- PATH_FIX_SUMMARY.md' newline ...
        '- FINAL_DEDUPLICATION.md' newline newline ...
        '---' newline newline ...
        '## 🚀 快速开始' newline newline ...
        '### 运行批量检测' newline newline ...
        '```matlab' newline ...
        'cd matlab' newline ...
        'matlab -batch "auto_run"' newline ...
        '```' newline newline ...
        '### 生成可视化图片' newline newline ...
        '```matlab' newline ...
        'cd matlab' newline ...
        'matlab -batch "batch_visualize_results()"' newline ...
        '```' newline newline ...
        '### 查看结果' newline newline ...
        '```matlab' newline ...
        'cd matlab' newline ...
        'matlab' newline ...
        '>> view_single_result(''defect_01'')' newline ...
        '```' newline newline ...
        '---' newline newline ...
        '## 📊 系统特性' newline newline ...
        '### v3.0-R6 核心功能' newline newline ...
        '1. ✅ **ROI自动检测** - 精确识别陶瓷管区域' newline ...
        '2. ✅ **不规则缺陷检测** - 全面检测所有类型缺陷' newline ...
        '3. ✅ **自动分类** - 4种缺陷类型（圆形、线状、空心、不规则）' newline ...
        '4. ✅ **高质量可视化** - 彩色标注、详细统计' newline ...
        '5. ✅ **批量处理** - 快速处理多张图片（~30秒/图）' newline newline ...
        '### 检测结果' newline newline ...
        '- **平均缺陷率**: 1.76%（相对ROI）' newline ...
        '- **平均检测数**: 19.5个缺陷/图' newline ...
        '- **质量评分**: 56.5/100' newline ...
        '- **ROI覆盖率**: 36.1%（精确管子区域）' newline newline ...
        '---' newline newline ...
        '## 🎨 可视化效果' newline newline ...
        '每张检测结果包含6个子图:' newline newline ...
        '1. 原始图像 + ROI边界（青色）' newline ...
        '2. CLAHE增强图' newline ...
        '3. ROI区域叠加' newline ...
        '4. 缺陷掩码（二值图）' newline ...
        '5. **缺陷分类标注**（彩色边界）' newline ...
        '   - 🟢 绿色：圆形孔洞' newline ...
        '   - 🔴 红色：线状裂纹' newline ...
        '   - 🟡 黄色：空心缺陷' newline ...
        '   - 🟣 洋红：不规则污渍' newline ...
        '6. 统计信息文本' newline newline ...
        '---' newline newline ...
        '## 📞 技术支持' newline newline ...
        '如有问题或建议，请参考:' newline ...
        '- 使用指南: `V3.0-R6_FINAL_GUIDE.md`' newline ...
        '- 版本历史: `../versions/CHANGELOG.md`' newline ...
        '- 项目主页: `../README.md`' newline newline ...
        '---' newline newline ...
        '**最后更新**: 2025-10-04  ' newline ...
        '**当前版本**: v3.0-R6（生产就绪）' newline];
    
    fid = fopen(readmePath, 'w', 'n', 'UTF-8');
    if fid ~= -1
        fprintf(fid, '%s', readmeContent);
        fclose(fid);
        fprintf('   ✓ 创建: docs/README.md\n');
    else
        fprintf('   ✗ 失败: 无法创建 docs/README.md\n');
    end
    
    fprintf('\n===== 整理完成 =====\n');
    fprintf('文档位置: docs/\n');
    fprintf('主文档: docs/V3.0-R6_FINAL_GUIDE.md\n');
    fprintf('索引: docs/README.md\n');
end

