function defaults = ceramic_default_options()
%CERAMIC_DEFAULT_OPTIONS 陶瓷缺陷检测的默认参数配置 - v2.0版本
%   DEFAULTS = CERAMIC_DEFAULT_OPTIONS() 返回默认的参数结构体

    defaults = struct( ...
        'ClipLimit', 0.015, ...
        'NumTiles', [8 8], ...
        'LocalBlockSize', [64 64], ...
        'LocalOverlap', [16 16], ...
        'MorphOpenRadius', 2, ...
        'CannyThreshold', [], ...
        'CannySigma', 1.0, ...
        'SobelThreshold', 0.02, ...
        'LineFillGap', 10, ...
        'LineMinLength', 30, ...
        'CircleRadius', [6 40], ...
        'CircleSensitivity', 0.9, ...
        'CircleEdgeThreshold', 0.1 ...
    );
end

